BEGIN_EVENT_TABLE(AstadeSearchDialog,generatedSearchDialog)
	EVT_CLOSE( AstadeSearchDialog::OnExit)
	EVT_CHECKBOX(ID_LookingForAll, AstadeSearchDialog::OnLookingForAll)
	EVT_CHECKBOX(ID_FieldsToSearchAll, AstadeSearchDialog::OnFieldsToSearchAll)
	EVT_CHECKBOX(ID_OptionRegularExpression, AstadeSearchDialog::OnOptionRegularExpression)
	EVT_BUTTON(ID_StartSearch, AstadeSearchDialog::OnStartSearch)
	EVT_BUTTON(ID_Cancel, AstadeSearchDialog::OnCancel)
END_EVENT_TABLE()
