#include "CodeEditControl.h"
// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Oct 22 15:00:46 2009

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GENERATEDFRAME_H
#define GENERATEDFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class GeneratedFrame: public wxFrame {
public:
    // begin wxGlade: GeneratedFrame::ids
    enum {
        LINE_NUMBER_BOX = wxID_HIGHEST + 1000,
        INDENT_BOX = wxID_HIGHEST + 1001,
        WHITESPACE_BOX = wxID_HIGHEST + 1002,
        SEARCH = wxID_HIGHEST + 1003,
        REPLACE = wxID_HIGHEST + 1004,
        CANCEL_BUTTON = wxID_HIGHEST + 1005,
        OK_BUTTON = wxID_HIGHEST + 1006
    };
    // end wxGlade

    GeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: GeneratedFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GeneratedFrame::attributes
    CodeEditControl* myEditControl;
    wxPanel* editPanel;
    wxCheckBox* lineNumbersBox;
    wxCheckBox* showIndentBox;
    wxCheckBox* whitespaceBox;
    wxButton* searchButton;
    wxButton* replaceButton;
    wxButton* cancel_button;
    wxButton* ok_button;
    wxPanel* buttonPanel;
    // end wxGlade
}; // wxGlade: end class


#endif // GENERATEDFRAME_H
