/* vi: set tabstop=4: */

target.SetExt("h");
std::ofstream out(target.GetFullPath());

wxFileName PrefixName(myAdeComponent->GetFileName());
PrefixName.SetFullName("prolog.h");
wxTextFile Gprefixtext(PrefixName.GetFullPath());
if (Gprefixtext.Exists())
	Gprefixtext.Open();
if (Gprefixtext.IsOpened())
{
	wxString str;
	for (str = Gprefixtext.GetFirstLine(); !Gprefixtext.Eof(); str = Gprefixtext.GetNextLine())
		out << str << std::endl;
	if (!str.empty())
		out << str << std::endl;
	out << std::endl;
}

out << "/******************************************************/" << std::endl;
out << "/* this code was generated by the Astade CppGenerator */" << std::endl;
out << "/** @mainpage " << myAdeComponent->GetDescription() << std::endl;
out << "*/" << std::endl;
out << "/** " << source->GetDescription()   << std::endl;
out << " *  @date " << GenerationTime       << std::endl;
out << " *  @file " << target.GetFullName() << std::endl;
out << " * " << source->GetDescription()    << std::endl;
out << " ******************************************************/" << std::endl;
out << std::endl;
 
wxString defname(target.GetFullName());
defname.MakeUpper();
defname.Replace(".","_");

out << "#ifndef __"   << defname << std::endl;
out << "  #define __" << defname << std::endl;
out << std::endl;

PrefixName = source->GetFileName();
PrefixName.SetFullName("prolog.h");
wxTextFile prefixtext(PrefixName.GetFullPath());
PrefixName.MakeRelativeTo(wxFileName::GetCwd());

if (prefixtext.Exists())
	prefixtext.Open();
if (prefixtext.IsOpened())
{
	out << "//****** specification prolog ******" << std::endl;
	out << "//[" << PrefixName.GetFullPath() << "]" << std::endl;
	wxString str;
	for (str = prefixtext.GetFirstLine(); !prefixtext.Eof(); str = prefixtext.GetNextLine())
		out << str << std::endl;
	if (!str.empty())
		out << str << std::endl;
	out << "//[EOF]" << std::endl;
	out << "//**********************************" << std::endl;
	out << std::endl;
}

wxString BaseClasses;
RelationIncludes(out, true, &BaseClasses);

if (!source->GetAdditionalBaseClasses().empty())
{
	if (!BaseClasses.empty())
		BaseClasses = source->GetAdditionalBaseClasses() + ", " + BaseClasses;
	else
		BaseClasses = source->GetAdditionalBaseClasses();
}
wxString description(source->GetDescription());
if (!description.empty())
{
	out << "/** " << description << std::endl;
	out << "*/"   << std::endl;
}
out << "class " << source->GetName();
if (!BaseClasses.empty())
	out << " : " << BaseClasses;
out << std::endl;
out << "{" << std::endl;

out << "public:" << std::endl;
staticAttribute(out, true, ITEM_IS_PUBLIC);
memberType(out);
memberAttribute(out, true, ITEM_IS_PUBLIC);
operations(out, true, false, ITEM_IS_PUBLIC);
out << std::endl;

out << "protected:" << std::endl;
staticAttribute(out, true, ITEM_IS_PROTECTED);
memberAttribute(out, true, ITEM_IS_PROTECTED);
relationAttribute(out);
operations(out, true, false, ITEM_IS_PROTECTED);
out << std::endl;

out << "private:" << std::endl;
staticAttribute(out, true, ITEM_IS_PRIVATE);
memberAttribute(out, true, ITEM_IS_PRIVATE);
operations(out, true, false, ITEM_IS_PRIVATE);

out << "};" << std::endl;
out << std::endl;

operations(out, false, true, ITEM_IS_PUBLIC);
operations(out, false, true, ITEM_IS_PROTECTED);
operations(out, false, true, ITEM_IS_PRIVATE);

wxFileName PostfixName(source->GetFileName());
PostfixName.SetFullName("epilog.h");
wxTextFile postfixtext(PostfixName.GetFullPath());
PostfixName.MakeRelativeTo(wxFileName::GetCwd());

if (postfixtext.Exists())
	postfixtext.Open();

if (postfixtext.IsOpened())
{
	out << "//****** specification epilog ******" << std::endl;
	out << "//[" << PostfixName.GetFullPath() << "]" << std::endl;
	wxString str;
	for (str = postfixtext.GetFirstLine(); !postfixtext.Eof(); str = postfixtext.GetNextLine())
		out << str << std::endl;
	if (!str.empty())
		out << str << std::endl;
	out << "//[EOF]" << std::endl;
	out << "//**********************************" << std::endl;
	out << std::endl;
}

out << "#endif" << std::endl;

PostfixName = myAdeComponent->GetFileName();
PostfixName.SetFullName("epilog.h");
wxTextFile Gpostfixtext(PostfixName.GetFullPath());
if (Gpostfixtext.Exists())
	Gpostfixtext.Open();
if (Gpostfixtext.IsOpened())
{
	out << std::endl;
	wxString str;
	for (str = Gpostfixtext.GetFirstLine(); !Gpostfixtext.Eof(); str = Gpostfixtext.GetNextLine())
		out << str << std::endl;
	if (!str.empty())
		out << str << std::endl;
}
