BEGIN_EVENT_TABLE(AstadeFrame,wxFrame)
	EVT_IDLE(AstadeFrame::OnIdle)

	EVT_TREE_ITEM_EXPANDING(ID_ASTADETREE, AstadeFrame::ExpandNode)
	EVT_TREE_ITEM_COLLAPSED(ID_ASTADETREE, AstadeFrame::CollapseNode)
	EVT_TREE_ITEM_MENU(ID_ASTADETREE,AstadeFrame::OnRightMouseClick)
	EVT_TREE_ITEM_ACTIVATED(ID_ASTADETREE, AstadeFrame::OnDoubleMouseClick)
	EVT_TREE_SEL_CHANGED(ID_ASTADETREE, AstadeFrame::OnSelChanged)

	EVT_TREE_BEGIN_DRAG(ID_ASTADETREE, AstadeFrame::OnDrag)
	EVT_UPDATE_UI(ID_ASTADETREE, AstadeFrame::DoUpdate)
	EVT_TIMER(TIMER_ID, AstadeFrame::OnTimer)
	EVT_MENU(ID_ACTIVECONFIGURATION, AstadeFrame::SetAsActive)
	EVT_MENU(ID_ADDRELATION, AstadeFrame::AddRelation)
	EVT_MENU(ID_ADDTOCOMPONENT, AstadeFrame::AddToComponent)
	EVT_MENU(ID_COMPLETERELATION, AstadeFrame::CompleteRelation)
	EVT_MENU(ID_COPYMAKEFILE, AstadeFrame::CopyMakefile)
	EVT_MENU(ID_COPYFILE, AstadeFrame::Copyfile)
	EVT_MENU(ID_COPY, AstadeFrame::Copy)
	EVT_MENU(ID_CUT, AstadeFrame::Cut)
	EVT_MENU(ID_PASTE, AstadeFrame::Paste)
	EVT_MENU(ID_DELETE, AstadeFrame::Delete)
	EVT_MENU(ID_DOWN, AstadeFrame::ParameterDown)
	EVT_MENU(ID_EDIT, AstadeFrame::Edit)
	EVT_MENU(ID_EDITIMPLEMENTATION, AstadeFrame::EditImplementation)
	EVT_MENU(ID_EDITSPECIFICATION, AstadeFrame::EditSpecification)
	EVT_MENU(ID_EDITSPECPROLOG, AstadeFrame::EditPrologEpilog)
	EVT_MENU(ID_EDITIMPPROLOG, AstadeFrame::EditPrologEpilog)
	EVT_MENU(ID_EDITSPECEPILOG, AstadeFrame::EditPrologEpilog)
	EVT_MENU(ID_EDITIMPGEPILOG, AstadeFrame::EditPrologEpilog)
	EVT_MENU(ID_FEATURES, AstadeFrame::Features)
	EVT_MENU(ID_GENCODE, AstadeFrame::CallCoder)
	EVT_MENU(ID_GENSTATECHART, AstadeFrame::CallStatechartCoder)
	EVT_MENU(ID_SHOW, AstadeFrame::ShowHtml)
	EVT_MENU(ID_JUMPORIG, AstadeFrame::JumpToPartner)
	EVT_MENU(ID_JUMPDEST, AstadeFrame::JumpToPartner)
	EVT_MENU(ID_RENAMEELEMENT, AstadeFrame::RenameElement)
	EVT_MENU(ID_MNU_HELP, AstadeFrame::DisplayHelp)
	EVT_MENU(ID_MNU_INFO, AstadeFrame::DisplayInfo)
	EVT_MENU(ID_MNU_ABOUT, AstadeFrame::DisplayAbout)
	EVT_MENU(ID_OBJECTMODELDIALOG, AstadeFrame::OmdDialog)
	EVT_MENU(ID_REGENERATE, AstadeFrame::Regenerate)
	EVT_MENU(ID_REENGINEER, AstadeFrame::ReEngineer)
	EVT_MENU(ID_REMOVEFROMCOMPONENT, AstadeFrame::RemoveFromComponent)
	EVT_MENU(ID_ROUNDTRIPCODE, AstadeFrame::Roundtrip)
	EVT_MENU(ID_SETEDITORS, AstadeFrame::DirDialog)
	EVT_MENU(ID_SETAPPS, AstadeFrame::AppDialog)
	EVT_MENU(ID_SETREGEX, AstadeFrame::RegExDialog)
	EVT_MENU(ID_STATECHART, AstadeFrame::DisplayStatechart)
	EVT_MENU(ID_UP, AstadeFrame::ParameterUp)
	EVT_MENU(ID_SELECTMODEL, AstadeFrame::SelectModel)
	EVT_MENU(ID_CREATEMODEL, AstadeFrame::CreateModel)
	EVT_MENU(ID_ADDSEQUENCEDIAGRAM, AstadeFrame::AddSequenceDiagram)
	EVT_MENU(ID_SEARCH, AstadeFrame::OpenSearchDialog)
	EVT_MENU(ID_SELECTNONE, AstadeFrame::SelectRepository)
	EVT_MENU(ID_SELECTSVN, AstadeFrame::SelectRepository)
	EVT_MENU(ID_SELECTGIT, AstadeFrame::SelectRepository)
	EVT_MENU(ID_SELECTCVS, AstadeFrame::SelectRepository)
	EVT_MENU(ID_SELECTMKS, AstadeFrame::SelectRepository)
	EVT_MENU(ID_ADDUSECASEDIAGRAM, AstadeFrame::AddUseCaseDiagram)
	EVT_MENU(ID_EXIT, AstadeFrame::OnExit)
	EVT_MENU(ID_MAKEMAINCPP, AstadeFrame::MakeMainCpp)
	EVT_MENU(ID_TABWIDTH, AstadeFrame::SetTabsize)
	EVT_MENU_RANGE(ID_JUMP,ID_JUMPMAX, AstadeFrame::JumpToClass)
	EVT_END_PROCESS(wxID_ANY, AstadeFrame::EndProcess)

	EVT_MENU_RANGE(ID_RECENT1,ID_RECENT4, AstadeFrame::SelectRecentModel)
	EVT_MENU_RANGE(ID_MAKEMIN,ID_MAKEMAX, AstadeFrame::CallMake)
	EVT_MENU_RANGE(ID_ADDMIN,ID_ADDMAX, AstadeFrame::AddSubElement)
	EVT_MENU_RANGE(ID_OVERLOADMIN,ID_OVERLOADMAX, AstadeFrame::OverloadOperation)

	EVT_MENU_RANGE(ID_TRACE_ON,ID_TRACE_OFF, AstadeFrame::OnTraceOnOff)
	EVT_MENU(ID_ALL_TRACE_OFF, AstadeFrame::OnAllTraceOff)

	EVT_MENU_RANGE(ID_MINTOOL, ID_MAXTOOL, AstadeFrame::OnToolClicked)
	EVT_TOOL_RANGE(ID_MINTOOL, ID_MAXTOOL, AstadeFrame::OnToolClicked)
	EVT_CHOICE(ID_TOOL_CONFIG, AstadeFrame::OnChoice)
	EVT_CHOICE(ID_TOOL_BUILDTARGET, AstadeFrame::OnChoice)
	EVT_CHOICE(ID_TOOL_RUNTARGET, AstadeFrame::OnChoice)
END_EVENT_TABLE()
