//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:25 UTC
//** Filename: SeqApplication.cpp
//******************************************************

//****** implementation prolog ******
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_LVBRXWZT/prolog.cpp]
#include "SeqApplication.h"
IMPLEMENT_APP(SeqApplication)
//[EOF]
//***********************************

#include "SeqApplication.h"	 // own header


bool SeqApplication::OnInit()
{
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_LVBRXWZT/operations/operation_FNIUZSGW/code.cpp]
	wxImage::AddHandler( new wxPNGHandler );
	wxImage::AddHandler( new wxJPEGHandler );
	
	myFrame = new  SeqFrame;
	SetTopWindow(myFrame);
	myFrame->Show(TRUE);
	
	if (argc > 1)
		myFrame->Load(argv[1]);
	
	return true;
//[EOF]
};

