//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:26 UTC
//** Filename: SeqEvent.cpp
//******************************************************

#include "SeqEvent.h"	 // own header


SeqEvent::SeqEvent(int source,int destination,int ID,const wxString& aLabel,wxString timeStamp) :
	aTimeStamp(timeStamp),
	destinationObject(destination),
	eventID(ID),
	label(aLabel),
	sourceObject(source),
	time(0)
{
};

