//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:26 UTC
//** Filename: SeqEvent.h
//******************************************************

#ifndef __SEQEVENT_H
  #define __SEQEVENT_H

//****** specification prolog ******
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_SIHIQFYE/prolog.h]
#include <wx/string.h>

#define ID_GLOBALCREATE 30000
#define ID_CREATE		30001
#define ID_CALL 		30002
#define ID_RETURN 		30003
#define ID_CLASSBOX		30004
#define ID_GLOBALDELETE 30005
#define ID_DELETE		30006
#define ID_NOP			30007
#define ID_COMMENT		30008
#define ID_SELFCALL		30009
#define ID_SELFRETURN	30010
#define ID_GLOBALCALL	30011
#define ID_GLOBALRETURN	30012
#define ID_SEND			30013
#define ID_SELFSEND		30014
#define ID_RECEIVE		30015
#define ID_SELFRECEIVE	30016
#define ID_EXIST		30017
#define ID_STATECHANGE	30018
//[EOF]
//**********************************


class SeqEvent
{
public:
	wxString	aTimeStamp;
	int	destinationObject;
	int	eventID;
	wxString	label;
	int	sourceObject;
	int	time;
	SeqEvent(int source,int destination,int ID,const wxString& aLabel,wxString timeStamp);

protected:

private:
};

#endif
