//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:14 UTC
//** Filename: SeqFrame.h
//******************************************************

#ifndef __SEQFRAME_H
  #define __SEQFRAME_H

//****** specification prolog ******
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_ARRSZHDE/prolog.h]
#include <wx/frame.h>
#include <wx/menu.h>
#include <wx/notebook.h>
#include <wx/filedlg.h>
#include <wx/textfile.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/filename.h>
#include <wx/choicdlg.h>
#include <wx/dcmemory.h>
#include <wx/msgdlg.h>

#define ID_OPEN			20000
#define ID_NOTEBOOK		20001
#define ID_SAVE			20002
#define ID_SAVEGRAPH	20003
#define ID_SAVEAS		20004
#define ID_ABOUT		20005
#define ID_COPYGRAPH	20006
//[EOF]
//**********************************

// Relation includes:
#include "SeqDataBase.h"
#include "SeqGraphTab.h"
#include "SeqTextTab.h"

class SeqFrame : public wxFrame
{
public:
	DECLARE_EVENT_TABLE()
public:
	SeqFrame();
	void Load(const wxString& dir);

protected:
	SeqDataBase*	dataBase;
	SeqGraphTab*	graphTab;
	SeqTextTab*	textTab;

private:
	wxString	currentFile;
	int	isChanged;
	wxNotebook*	noteBook;
	void SaveBitmap(const wxBitmap& bitMap);
	void Open(wxCommandEvent& event);
	void Save(wxCommandEvent& event);
	void SaveFileAs(wxCommandEvent& event);
	void Exit(wxCloseEvent& event);
	void CopyBitmap(wxCommandEvent& event);
	void About(wxCommandEvent& event);
	void SaveGraphic(wxCommandEvent& event);
	void GenText(wxNotebookEvent& event);
};

#endif
