//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:29 UTC
//** Filename: SeqTextTab.h
//******************************************************

#ifndef __SEQTEXTTAB_H
  #define __SEQTEXTTAB_H

//****** specification prolog ******
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_VWXPMXLN/prolog.h]
#include <wx/textctrl.h>
//[EOF]
//**********************************

// Relation includes:
#include "SeqDataBase.h"

class SeqTextTab : public wxTextCtrl
{
public:
	SeqTextTab(wxWindow* parent);
	void SetDefaultStyle();

protected:
	SeqDataBase*	dataBase;

private:
};

#endif
