//******************************************************
//** Code generated by the Astade CppGenerator
//** Date:     2006-03-03 12:29:29 UTC
//** Filename: SeqTextTab.cpp
//******************************************************

#include "SeqTextTab.h"	 // own header


SeqTextTab::SeqTextTab(wxWindow* parent) :
	wxTextCtrl(parent,-1, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_RICH | wxTE_DONTWRAP)
{
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_VWXPMXLN/operations/constructor_XFBZRZEO/code.cpp]
	SetDefaultStyle();
//[EOF]
};

void SeqTextTab::SetDefaultStyle()
{
//[/Users/stefan/Developer/Astade-UML/trace2uml/Model/Package_LEOIFVGO/classes/class_VWXPMXLN/operations/operation_CTSPWLWB/code.cpp]
	wxTextAttr anAttr = GetDefaultStyle();
	
	wxFont aFont(anAttr.GetFont());
	aFont.SetFamily(wxFONTFAMILY_MODERN);
	anAttr.SetFont(aFont);
	anAttr.SetTextColour(*wxBLACK);
	
	wxTextCtrl::SetDefaultStyle(anAttr);
//[EOF]
};

