/******************************************************/
/* this code was generated by the Astade CppGenerator */
/** 
 *  @date 2008-05-21 11:59:48 UTC
 *  @file CApp.h
 ******************************************************/

#ifndef __CAPP_H
#  define __CAPP_H



class CApp
{

public:

protected:

private:
};

#endif
