Refresh();
AddMenuSeparator();
AddMenuFunction(wxS("Dependancy"), wxCommandEventHandler(glRelation::OnDependancy));
AddMenuFunction(wxS("Association"), wxCommandEventHandler(glRelation::OnAssociation));
AddMenuFunction(wxS("Aggregation"), wxCommandEventHandler(glRelation::OnAggregation));
AddMenuFunction(wxS("Composition"), wxCommandEventHandler(glRelation::OnComposition));
AddMenuFunction(wxS("Generalization"), wxCommandEventHandler(glRelation::OnGeneralization));
AddMenuFunction(wxS("Realization"), wxCommandEventHandler(glRelation::OnRealization));
AddMenuSeparator();
AddMenuFunction(wxS("End point mult"), wxCommandEventHandler(glRelation::OnEndMult));
AddMenuFunction(wxS("Start point mult"), wxCommandEventHandler(glRelation::OnStartMult));
