BEGIN_EVENT_TABLE(AstadeAppDialog,wxDialog)
	EVT_CLOSE(AstadeAppDialog::DlgClose)
	EVT_BUTTON(wxID_CANCEL, AstadeAppDialog::DlgCancel)
	EVT_BUTTON(wxID_OK, AstadeAppDialog::DlgSaveAndExit)
	EVT_BUTTON(ID_BUTTON_ADD, AstadeAppDialog::OnAdd)
	EVT_BUTTON(ID_BUTTON_REMOVE, AstadeAppDialog::OnRemove)
	EVT_BUTTON(ID_BUTTON_UPDATE, AstadeAppDialog::OnUpdate)
	EVT_LIST_ITEM_SELECTED(ID_LISTCTRL_APPS, AstadeAppDialog::OnSelected)
END_EVENT_TABLE()