// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Dec 15 11:11:11 2010

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GENERATEDREVERSEENGINEERFRAME_H
#define GENERATEDREVERSEENGINEERFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class GeneratedReverseEngineerFrame: public wxFrame {
public:
    // begin wxGlade: GeneratedReverseEngineerFrame::ids
    enum {
        SOURCEWINDOW = wxID_HIGHEST + 1000,
        DESTINATIONWINDOW = wxID_HIGHEST + 1001
    };
    // end wxGlade

    GeneratedReverseEngineerFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: GeneratedReverseEngineerFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GeneratedReverseEngineerFrame::attributes
    wxStaticBox* destinationSizer_staticbox;
    wxStaticBox* sourceSizer_staticbox;
    wxTextCtrl* source;
    wxPanel* sourcePanel;
    wxTextCtrl* destination;
    wxPanel* destinationPanel;
    // end wxGlade
}; // wxGlade: end class


#endif // GENERATEDREVERSEENGINEERFRAME_H
