// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Dec 15 11:11:11 2010

#include "GeneratedReverseEngineerFrame.h"

// begin wxGlade: ::extracode

// end wxGlade


GeneratedReverseEngineerFrame::GeneratedReverseEngineerFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: GeneratedReverseEngineerFrame::GeneratedReverseEngineerFrame
    destinationPanel = new wxPanel(this, wxID_ANY);
    sourcePanel = new wxPanel(this, wxID_ANY);
    destinationSizer_staticbox = new wxStaticBox(destinationPanel, -1, wxT("Parsed result"));
    sourceSizer_staticbox = new wxStaticBox(sourcePanel, -1, wxT("Text to parse"));
    source = new wxTextCtrl(sourcePanel, SOURCEWINDOW, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    destination = new wxTextCtrl(destinationPanel, DESTINATIONWINDOW, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);

    set_properties();
    do_layout();
    // end wxGlade
}


void GeneratedReverseEngineerFrame::set_properties()
{
    // begin wxGlade: GeneratedReverseEngineerFrame::set_properties
    SetTitle(wxT("ReverseEngeneer"));
    SetSize(wxSize(449, 343));
    destination->Enable(false);
    // end wxGlade
}


void GeneratedReverseEngineerFrame::do_layout()
{
    // begin wxGlade: GeneratedReverseEngineerFrame::do_layout
    wxBoxSizer* mainSizer = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* destinationSizer = new wxStaticBoxSizer(destinationSizer_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* sourceSizer = new wxStaticBoxSizer(sourceSizer_staticbox, wxHORIZONTAL);
    sourceSizer->Add(source, 1, wxEXPAND, 0);
    sourcePanel->SetSizer(sourceSizer);
    mainSizer->Add(sourcePanel, 1, wxEXPAND, 0);
    destinationSizer->Add(destination, 1, wxEXPAND, 0);
    destinationPanel->SetSizer(destinationSizer);
    mainSizer->Add(destinationPanel, 1, wxEXPAND, 0);
    SetSizer(mainSizer);
    Layout();
    // end wxGlade
}

