// -*- C++ -*- generated by wxGlade 0.5 on Sat Jan 03 14:04:19 2009 from C:\Dokumente und Einstellungen\Thomas\Eigene Dateien\Astade\Model\components_WGNBOFKH\Component_CDFBZLFN\manual\dialogs.wxg

#include "glGeneratedFrame.h"


glGeneratedFrame::glGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: glGeneratedFrame::glGeneratedFrame
    frame_menubar = new wxMenuBar();
    SetMenuBar(frame_menubar);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    panel_1 = new wxPanel(this, wxID_ANY);
    button_1 = new wxButton(this, wxID_ANY, wxT("button_1"));

    set_properties();
    do_layout();
    // end wxGlade
}


void glGeneratedFrame::set_properties()
{
    // begin wxGlade: glGeneratedFrame::set_properties
    SetTitle(wxT("frame_1"));
    // end wxGlade
}


void glGeneratedFrame::do_layout()
{
    // begin wxGlade: glGeneratedFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    sizer_1->Add(button_1, 0, 0, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

