// -*- C++ -*- generated by wxGlade 0.5 on Mon Jan 12 12:09:01 2009 from d:\Dokumente und Einstellungen\spitzer\Eigene Dateien\Astade\Model\components_WGNBOFKH\Component_CDFBZLFN\manual\dialogs.wxg

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GLGENERATEDFRAME_H
#define GLGENERATEDFRAME_H

#include "glGraphicPanel.h"

// begin wxGlade: ::dependencies
// end wxGlade


class glGeneratedFrame: public wxFrame {
public:
    // begin wxGlade: glGeneratedFrame::ids
    enum {
        ID_graphicPanel = wxID_HIGHEST + 1000,
        ID_SpeedBox = wxID_HIGHEST + 1001,
        ID_xPixelSlider = wxID_HIGHEST + 1002,
        ID_yPixelSlider = wxID_HIGHEST + 1003
    };
    // end wxGlade

    glGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: glGeneratedFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: glGeneratedFrame::attributes
    wxStaticBox* sliderSizer_staticbox;
    wxMenuBar* myMenuBar;
    glGraphicPanel* graphicPanel;
    wxRadioBox* speedBox;
    wxSlider* xPixelSlider;
    wxSlider* yPixelSlider;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // GLGENERATEDFRAME_H
