// -*- C++ -*- generated by wxGlade 0.5 on Sat Jan 03 14:04:19 2009 from C:\Dokumente und Einstellungen\Thomas\Eigene Dateien\Astade\Model\components_WGNBOFKH\Component_CDFBZLFN\manual\dialogs.wxg

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GLGENERATEDFRAME_H
#define GLGENERATEDFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade


class glGeneratedFrame: public wxFrame {
public:
    // begin wxGlade: glGeneratedFrame::ids
    // end wxGlade

    glGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: glGeneratedFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: glGeneratedFrame::attributes
    wxMenuBar* frame_menubar;
    wxPanel* panel_1;
    wxButton* button_1;
    // end wxGlade
}; // wxGlade: end class


#endif // GLGENERATEDFRAME_H
