// -*- C++ -*- generated by wxGlade 0.5 on Sun Jan 04 09:31:11 2009 from C:\Dokumente und Einstellungen\Thomas\Eigene Dateien\Astade\Model\components_WGNBOFKH\Component_CDFBZLFN\manual\dialogs.wxg

#include "glGeneratedFrame.h"


glGeneratedFrame::glGeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: glGeneratedFrame::glGeneratedFrame
    panel_1 = new wxPanel(this, wxID_ANY);
    frame_menubar = new wxMenuBar();
    SetMenuBar(frame_menubar);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu_2, wxT("Panelsize"));
    graphicPanel = new wxPanel(this, wxID_ANY);
    const wxString radio_box_1_choices[] = {
        wxT("slow"),
        wxT("normal"),
        wxT("fast"),
        wxT("fastest")
    };
    radio_box_1 = new wxRadioBox(panel_1, wxID_ANY, wxT("update speed"), wxDefaultPosition, wxDefaultSize, 4, radio_box_1_choices, 4, wxRA_SPECIFY_COLS);

    set_properties();
    do_layout();
    // end wxGlade
}


void glGeneratedFrame::set_properties()
{
    // begin wxGlade: glGeneratedFrame::set_properties
    SetSize(wxSize(610, 506));
    radio_box_1->SetSelection(1);
    // end wxGlade
}


void glGeneratedFrame::do_layout()
{
    // begin wxGlade: glGeneratedFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(graphicPanel, 1, wxEXPAND, 0);
    sizer_2->Add(radio_box_1, 1, wxEXPAND, 0);
    panel_1->SetSizer(sizer_2);
    sizer_1->Add(panel_1, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

