module_init(trace2uml_driver_init);
module_exit(trace2uml_driver_exit);

EXPORT_SYMBOL(trace2uml_driver_notify_function_call);
EXPORT_SYMBOL(trace2uml_driver_notify_constructor);
EXPORT_SYMBOL(trace2uml_driver_notify_destructor);
EXPORT_SYMBOL(trace2uml_driver_notify_return);
