BEGIN_EVENT_TABLE(glGraphicPanel,wxScrolledWindow)
	EVT_TIMER(ID_RefreshTimer,glGraphicPanel::OnRefreshTimer)
	EVT_TIMER(ID_MoveTimer,glGraphicPanel::OnMoveTimer)
	EVT_RIGHT_UP(glGraphicPanel::OnRightUp)
	EVT_MENU(wxID_ANY, glGraphicPanel::CreateObject)
	EVT_IDLE(glGraphicPanel::OnIdle)
	EVT_ENTER_WINDOW(glGraphicPanel::OnMouseMove)
	EVT_LEAVE_WINDOW(glGraphicPanel::OnMouseLeave)
	EVT_MOTION(glGraphicPanel::OnMouseMove)
END_EVENT_TABLE()