// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Sep 27 07:57:34 2007

#include "GeneratedFrame.h"


GeneratedFrame::GeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxCAPTION|wxRESIZE_BORDER)
{
    // begin wxGlade: GeneratedFrame::GeneratedFrame
    buttonPanel = new wxPanel(this, -1);
    editPanel = new wxPanel(this, -1);
    myEditControl = new CodeEditControl(editPanel, -1);
    lineNumbersBox = new wxCheckBox(buttonPanel, LINE_NUMBER_BOX, wxT("line numbers"));
    showIndentBox = new wxCheckBox(buttonPanel, INDENT_BOX, wxT("show indent"));
    whitespaceBox = new wxCheckBox(buttonPanel, WHITESPACE_BOX, wxT("show whitespace"));
    searchButton = new wxButton(buttonPanel, SEARCH, wxT("search"));
    cancel_button = new wxButton(buttonPanel, CANCEL_BUTTON, wxT("Cancel"));
    ok_button = new wxButton(buttonPanel, OK_BUTTON, wxT("OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


void GeneratedFrame::set_properties()
{
    // begin wxGlade: GeneratedFrame::set_properties
    SetSize(wxSize(655, 475));
    // end wxGlade
}


void GeneratedFrame::do_layout()
{
    // begin wxGlade: GeneratedFrame::do_layout
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer = new wxFlexGridSizer(2, 2, 0, 0);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(myEditControl, 1, wxEXPAND, 0);
    editPanel->SetAutoLayout(true);
    editPanel->SetSizer(sizer_1);
    sizer_1->Fit(editPanel);
    sizer_1->SetSizeHints(editPanel);
    mainSizer->Add(editPanel, 1, wxEXPAND, 0);
    grid_sizer->Add(lineNumbersBox, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 5);
    grid_sizer->Add(showIndentBox, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 5);
    grid_sizer->Add(whitespaceBox, 0, wxLEFT|wxRIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer->Add(0, 0, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
    buttonSizer->Add(grid_sizer, 0, 0, 0);
    buttonSizer->Add(searchButton, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 10);
    buttonSizer->Add(0, 0, 1, wxEXPAND|wxADJUST_MINSIZE, 0);
    buttonSizer->Add(cancel_button, 0, wxRIGHT|wxTOP|wxBOTTOM, 10);
    buttonSizer->Add(ok_button, 0, wxRIGHT|wxTOP|wxBOTTOM, 10);
    buttonPanel->SetAutoLayout(true);
    buttonPanel->SetSizer(buttonSizer);
    buttonSizer->Fit(buttonPanel);
    buttonSizer->SetSizeHints(buttonPanel);
    mainSizer->Add(buttonPanel, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(mainSizer);
    Layout();
    // end wxGlade
}

