// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Sep 27 07:57:34 2007

#include "GeneratedFrame.h"


GeneratedFrame::GeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxCAPTION|wxRESIZE_BORDER)
{
    // begin wxGlade: GeneratedFrame::GeneratedFrame
    buttonPanel = new wxPanel(this, -1);
    editPanel = new wxPanel(this, -1);
    myEditControl = new CodeEditControl(editPanel, -1);
    lineNumbersBox = new wxCheckBox(buttonPanel, LINE_NUMBER_BOX, wxT("line numbers"));
    checkbox_2 = new wxCheckBox(buttonPanel, -1, wxT("checkbox_2"));
    checkbox_3 = new wxCheckBox(buttonPanel, -1, wxT("checkbox_3"));
    checkbox_4 = new wxCheckBox(buttonPanel, -1, wxT("checkbox_4"));
    checkbox_5 = new wxCheckBox(buttonPanel, -1, wxT("checkbox_5"));
    checkbox_6 = new wxCheckBox(buttonPanel, -1, wxT("checkbox_6"));
    cancel_button = new wxButton(buttonPanel, CANCEL_BUTTON, wxT("Cancel"));
    ok_button = new wxButton(buttonPanel, OK_BUTTON, wxT("OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


void GeneratedFrame::set_properties()
{
    // begin wxGlade: GeneratedFrame::set_properties
    SetSize(wxSize(589, 475));
    // end wxGlade
}


void GeneratedFrame::do_layout()
{
    // begin wxGlade: GeneratedFrame::do_layout
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 3, 0, 0);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(myEditControl, 1, wxEXPAND, 0);
    editPanel->SetAutoLayout(true);
    editPanel->SetSizer(sizer_1);
    sizer_1->Fit(editPanel);
    sizer_1->SetSizeHints(editPanel);
    mainSizer->Add(editPanel, 1, wxEXPAND, 0);
    grid_sizer_1->Add(lineNumbersBox, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 5);
    grid_sizer_1->Add(checkbox_2, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 5);
    grid_sizer_1->Add(checkbox_3, 0, wxLEFT|wxRIGHT|wxTOP|wxADJUST_MINSIZE, 5);
    grid_sizer_1->Add(checkbox_4, 0, wxLEFT|wxRIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_1->Add(checkbox_5, 0, wxLEFT|wxRIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_1->Add(checkbox_6, 0, wxLEFT|wxRIGHT|wxADJUST_MINSIZE, 5);
    buttonSizer->Add(grid_sizer_1, 1, wxEXPAND, 0);
    buttonSizer->Add(cancel_button, 0, wxRIGHT|wxTOP|wxBOTTOM|wxALIGN_RIGHT, 10);
    buttonSizer->Add(ok_button, 0, wxRIGHT|wxTOP|wxBOTTOM|wxALIGN_RIGHT, 10);
    buttonPanel->SetAutoLayout(true);
    buttonPanel->SetSizer(buttonSizer);
    buttonSizer->Fit(buttonPanel);
    buttonSizer->SetSizeHints(buttonPanel);
    mainSizer->Add(buttonPanel, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(mainSizer);
    Layout();
    // end wxGlade
}

