// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Sep 27 07:57:34 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GENERATEDFRAME_H
#define GENERATEDFRAME_H

#include "CodeEditControl.h"

// begin wxGlade: ::dependencies
// end wxGlade


class GeneratedFrame: public wxFrame {
public:
    // begin wxGlade: GeneratedFrame::ids
    enum {
        LINE_NUMBER_BOX = wxID_HIGHEST + 1000,
        CANCEL_BUTTON = wxID_HIGHEST + 1001,
        OK_BUTTON = wxID_HIGHEST + 1002
    };
    // end wxGlade

    GeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: GeneratedFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GeneratedFrame::attributes
    CodeEditControl* myEditControl;
    wxPanel* editPanel;
    wxCheckBox* lineNumbersBox;
    wxCheckBox* checkbox_2;
    wxCheckBox* checkbox_3;
    wxCheckBox* checkbox_4;
    wxCheckBox* checkbox_5;
    wxCheckBox* checkbox_6;
    wxButton* cancel_button;
    wxButton* ok_button;
    wxPanel* buttonPanel;
    // end wxGlade
}; // wxGlade: end class


#endif // GENERATEDFRAME_H
