// -*- C++ -*- generated by wxGlade 0.4.1 on Wed Sep 12 07:31:15 2007

#include "GeneratedFrame.h"


GeneratedFrame::GeneratedFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxICONIZE|wxCAPTION|wxMINIMIZE|wxMINIMIZE_BOX|wxMAXIMIZE|wxMAXIMIZE_BOX|wxSYSTEM_MENU|wxRESIZE_BORDER)
{
    // begin wxGlade: GeneratedFrame::GeneratedFrame
    buttonPanel = new wxPanel(this, -1);
    editPanel = new wxPanel(this, -1);
    generatedFrame_statusbar = CreateStatusBar(1, 0);
    myEditControl = new EditControl(editPanel, -1);
    cancel_button = new wxButton(buttonPanel, CANCEL_BUTTON, wxT("Cancel"));
    ok_button = new wxButton(buttonPanel, OK_BUTTON, wxT("OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


void GeneratedFrame::set_properties()
{
    // begin wxGlade: GeneratedFrame::set_properties
    SetSize(wxSize(589, 475));
    int generatedFrame_statusbar_widths[] = { -1 };
    generatedFrame_statusbar->SetStatusWidths(1, generatedFrame_statusbar_widths);
    const wxString generatedFrame_statusbar_fields[] = {
        wxT("generatedFrame_statusbar")
    };
    for(int i = 0; i < generatedFrame_statusbar->GetFieldsCount(); ++i) {
        generatedFrame_statusbar->SetStatusText(generatedFrame_statusbar_fields[i], i);
    }
    // end wxGlade
}


void GeneratedFrame::do_layout()
{
    // begin wxGlade: GeneratedFrame::do_layout
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(myEditControl, 1, wxEXPAND, 0);
    editPanel->SetAutoLayout(true);
    editPanel->SetSizer(sizer_1);
    sizer_1->Fit(editPanel);
    sizer_1->SetSizeHints(editPanel);
    mainSizer->Add(editPanel, 1, wxEXPAND, 0);
    buttonSizer->Add(0, 0, 1, wxADJUST_MINSIZE, 0);
    buttonSizer->Add(cancel_button, 0, wxRIGHT|wxTOP|wxBOTTOM|wxALIGN_RIGHT|wxADJUST_MINSIZE, 10);
    buttonSizer->Add(ok_button, 0, wxRIGHT|wxTOP|wxBOTTOM|wxALIGN_RIGHT|wxADJUST_MINSIZE, 10);
    buttonPanel->SetAutoLayout(true);
    buttonPanel->SetSizer(buttonSizer);
    buttonSizer->Fit(buttonPanel);
    buttonSizer->SetSizeHints(buttonPanel);
    mainSizer->Add(buttonPanel, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(mainSizer);
    Layout();
    // end wxGlade
}

