// Class automatically generated by Dev-C++ New Class wizard

#include "astadetree.h" // class's header file
#include "ctreeitemdata.h"
#include <wx/icon.h>


// class constructor
CAstadeTree::CAstadeTree(wxWindow* parent,
                  wxWindowID id, 
                  const wxPoint& pos, 
                  const wxSize& size, 
                  long style, 
                  const wxValidator& validator,
                  const wxString& name) : wxTreeCtrl(parent,id,pos,size,style,validator,name)
{
	// insert your code here
 }

// class destructor
CAstadeTree::~CAstadeTree()
{
	// insert your code here
}

void CAstadeTree::SortChildren(const wxTreeItemId& item)
{
    wxTreeItemIdValue cookie;
    wxTreeItemId item1 = GetFirstChild(item,cookie);
    wxTreeItemData* data;
    do
    {
        data = GetItemData(item1);
        if (data)
        {
            int type = static_cast<CTreeItemData*>(data)->type;
            type |= ITEM_IS_STATIC|ITEM_IS_VIRTUAL;
            char Buffer[50];
            sprintf(Buffer,"%u",type);
            static_cast<CTreeItemData*>(data)->tmp = GetItemText(item1);
            wxString sortText = Buffer + static_cast<CTreeItemData*>(data)->tmp;
            SetItemText(item1,sortText);
        }    
        item1 = GetNextChild(item,cookie);
    } while (data);
    wxTreeCtrl::SortChildren(item);    
    item1 = GetFirstChild(item,cookie);
    do
    {
        data = GetItemData(item1);
        if (data)
        {
            SetItemText(item1,static_cast<CTreeItemData*>(data)->tmp);
        }    
        item1 = GetNextChild(item,cookie);
    } while (data);
}   
