// Class automatically generated by Dev-C++ New Class wizard

#include "astadetree.h" // class's header file
#include "ctreeitemdata.h"
#include <wx/icon.h>

IMPLEMENT_DYNAMIC_CLASS(CAstadeTree,wxTreeCtrl);

// class constructor
CAstadeTree::CAstadeTree(){};

CAstadeTree::CAstadeTree(wxWindow* parent,
                  wxWindowID id, 
                  const wxPoint& pos, 
                  const wxSize& size, 
                  long style, 
                  const wxValidator& validator,
                  const wxString& name) : wxTreeCtrl(parent,id,pos,size,style,validator,name)
{
	// insert your code here
}

// class destructor
CAstadeTree::~CAstadeTree()
{
	// insert your code here
}


int CAstadeTree::OnCompareItems(const wxTreeItemId& item1, const wxTreeItemId& item2)
{
    wxTreeItemData* data1 = GetItemData(item1);
    wxTreeItemData* data2 = GetItemData(item2);
    int type1 = static_cast<CTreeItemData*>(data1)->type;
    int type2 = static_cast<CTreeItemData*>(data2)->type;
    return type1-type2;
}

